version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - 8080:443
    networks:
      - app-network
    command: [nginx-debug, '-g', 'daemon off;']
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 19861609
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    networks:
      - app-network
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 19861609
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    networks:
      - app-network
    tty: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 19861609
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: 19861609
    ports:
      - 33061:3306
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    networks:
      - app-network
  mysql-test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 19861609
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: root
      MYSQL_PASSWORD: 19861609
    ports:
      - 33062:3306
    volumes:
      - ./storage/docker/mysql-test:/var/lib/mysql
    networks:
      - app-network
  redis:
    image: redis:4.0
    ports:
      - 63791:6379
    networks:
      - app-network
  node:
    image: node:10.15.3-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    #    container_name: es01
    environment:
#      - node.name=es01
#      - discovery.seed_hosts=es02
#      - cluster.initial_master_nodes=es01,es02
#      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
