openapi: 3.0.0
info:
  title: 'Board API'
  description: 'HTTP JSON API'
  contact:
    name: 'Laravel api'
  license:
    name: Mr.Dow
  version: 1.0.0
servers:
  -
    url: /api
    description: 'API server'
paths:
  /adverts:
    get:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\Adverts\AdvertController::index'
      parameters:
        -
          name: region
          in: query
          description: 'Point of region''s id'
          required: true
        -
          name: category
          in: query
          description: 'Point of category''s id'
          required: true
        -
          name: pagination
          in: query
          description: 'pagination, default 1'
          required: false
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertListResource'
      security:
        -
          Bearer: []
          OAuth2: []
  '/adverts/{advertId}':
    get:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\Adverts\AdvertController::show'
      parameters:
        -
          name: advertId
          in: path
          description: 'ID of advert'
          required: true
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertShowResource'
      security:
        -
          Bearer: []
          OAuth2: []
  '/adverts/{advertId}/favorite':
    post:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\Adverts\FavoriteController::add'
      parameters:
        -
          name: advertId
          in: path
          required: true
      responses:
        '201':
          description: 'Success response'
      security:
        -
          Bearer: []
          OAuth2: []
    delete:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\Adverts\FavoriteController::remove'
      parameters:
        -
          name: advertId
          in: path
          required: true
      responses:
        '204':
          description: 'Success response'
      security:
        -
          Bearer: []
          OAuth2: []
  /register:
    post:
      tags:
        - Profile
      operationId: 'App\Http\Controllers\Api\Auth\RegisterController::register'
      requestBody:
        description: 'A object that needs to be added to be register'
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                email:
                  type: string
                pasword:
                  type: string
              type: object
      responses:
        '201':
          description: 'Success response'
          content:
            application/json:
              schema:
                property: version
                type: string
  /:
    get:
      tags:
        - Info
      operationId: 'App\Http\Controllers\Api\HomeController::home'
      responses:
        '200':
          description: 'API version'
          content:
            application/json:
              schema:
                property: version
                type: string
  /user/adserts:
    get:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\User\AdvertController::index'
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertListResource'
      security:
        -
          Bearer: []
          OAuth2: []
  '/user/adverts/{advertId}':
    get:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\User\AdvertController::show'
      parameters:
        -
          name: advertId
          in: path
          description: 'ID of advert'
          required: true
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertShowResource'
      security:
        -
          Bearer: []
          OAuth2: []
    put:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\User\AdvertController::update'
      parameters:
        -
          name: advertId
          in: path
          description: 'ID of advert'
          required: true
      requestBody:
        description: 'update user''s advert'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditRequest'
      responses:
        '201':
          description: 'Success response'
      security:
        -
          Bearer: []
          OAuth2: []
    delete:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\User\AdvertController::destroy'
      parameters:
        -
          name: advertId
          in: path
          required: true
      responses:
        '204':
          description: 'Success response'
      security:
        -
          Bearer: []
          OAuth2: []
  '/user/adverts/create/{category}/{region}':
    post:
      tags:
        - Adverts
      operationId: 'App\Http\Controllers\Api\User\AdvertController::store'
      parameters:
        -
          name: category
          in: path
          description: 'ID of category'
          required: true
        -
          name: region
          in: path
          description: 'ID of region'
          required: true
      requestBody:
        description: 'update user''s advert'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequest'
      responses:
        '201':
          description: 'Success response'
      security:
        -
          Bearer: []
          OAuth2: []
  /user/favorites:
    get:
      tags:
        - Favorites
      operationId: 'App\Http\Controllers\Api\User\FavoriteController::index'
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvertDetailResource'
      security:
        -
          Bearer: []
          OAuth2: []
  '/user/favorites/{advertId}':
    delete:
      tags:
        - Favorites
      operationId: 'App\Http\Controllers\Api\User\FavoriteController::remove'
      parameters:
        -
          name: advertId
          in: path
          required: true
      responses:
        '204':
          description: 'Success response'
      security:
        -
          Bearer: []
          OAuth2: []
  /user:
    get:
      tags:
        - Profile
      operationId: 'App\Http\Controllers\Api\User\ProfileController::show'
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
    put:
      tags:
        - Profile
      operationId: 'App\Http\Controllers\Api\User\ProfileController::update'
      requestBody:
        description: 'update user''s profile'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileEditRequest'
      responses:
        '200':
          description: 'Success response'
      security:
        -
          Bearer: []
          OAuth2: []
components:
  schemas:
    CreateRequest:
      properties:
        title:
          type: string
        content:
          type: string
        price:
          type: string
        address:
          type: string
      type: aplication/json
    EditRequest:
      properties:
        title:
          type: string
        content:
          type: string
        price:
          type: string
        address:
          type: string
      type: aplication/json
    ProfileEditRequest:
      properties:
        name:
          type: string
        last_name:
          type: string
        phone:
          type: string
      type: application/json
    AdvertDetailResource:
      properties:
        id:
          type: integer
        user_name:
          type: string
        category:
          type: string
        region:
          type: string
        phone:
          type: string
        title:
          type: string
        content:
          type: string
        price:
          type: string
        address:
          type: string
        published:
          type: string
        expires:
          type: string
      type: aplication/json
    AdvertListResource:
      properties:
        id:
          type: integer
        name:
          type: string
      type: application/json
    AdvertShowResource:
      properties:
        id:
          type: integer
        user_name:
          type: string
        phone:
          type: string
        category:
          type: integer
        region:
          type: integer
        title:
          type: string
        content:
          type: string
        price:
          type: string
        address:
          type: string
        published:
          type: string
        expires:
          type: string
      type: application/json
    Profile:
      properties:
        id:
          type: integer
        name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
      type: application/json
  securitySchemes:
    OAuth2:
      type: oauth2
      description: 'Use a global client_id / client_secret and your username / password combo to obtain a token'
      flows:
        password:
          tokenUrl: 'https://localhost:8080/oauth/token'
          scopes:
            description: 'You can use all functions in this site'
    Bearer:
      type: apiKey
      name: Authorization
      in: header
